### ISSUE TITLE
workspace/didChangeConfiguration

### ISSUE THREAD

**Issue by rwols** [openlawlibrary/pygls#115]
This notification is sent from editor to server upon startup.

vscode-json and vscode-eslint servers rely on this notification to be sent during startup, or they won't work.

So we notify the server regardless.

This framework throws an exception when encountering an unhandled notification. I think it should instead log a neutral message. Something like: "unhandled notification workspace/didChangeConfiguration".

The JSON-RPC spec states that clients/servers are free to ignore notifications, so this should not raise a hard exception.

**Comment by rwols** [comment]
Some logs (cc @pappasam):

```
::  -> jedi-language-server workspace/didChangeConfiguration: {'settings': {'jedi': {'diagnostics': {'didSave': True, 'didChange': True, 'didOpen': True, 'enabled': True}, 'completion': {'triggerCharacters': ['.']}, 'enabled': True, 'signnatureHelp': {'triggerCharacters': ['(', ',']}}}}
jedi-language-server: Failed to handle notification workspace/didChangeConfiguration: Object(settings=Object(jedi=Object(diagnostics=Object(didSave=True, didChange=True, didOpen=True, enabled=True), completion=Object(triggerCharacters=['.']), enabled=True, signnatureHelp=Object(triggerCharacters=['(', ',']))))
jedi-language-server: Traceback (most recent call last):
jedi-language-server: File "/home/raoul/.local/lib/python3.7/site-packages/pygls/protocol.py", line 280, in _get_handler
jedi-language-server: return self.fm.builtin_features[feature_name]
jedi-language-server: KeyError: 'workspace/didChangeConfiguration'
jedi-language-server: 
jedi-language-server: During handling of the above exception, another exception occurred:
jedi-language-server: 
jedi-language-server: Traceback (most recent call last):
jedi-language-server: File "/home/raoul/.local/lib/python3.7/site-packages/pygls/protocol.py", line 283, in _get_handler
jedi-language-server: return self.fm.features[feature_name]
jedi-language-server: KeyError: 'workspace/didChangeConfiguration'
jedi-language-server: 
jedi-language-server: During handling of the above exception, another exception occurred:
jedi-language-server: 
jedi-language-server: Traceback (most recent call last):
jedi-language-server: File "/home/raoul/.local/lib/python3.7/site-packages/pygls/protocol.py", line 307, in _handle_notification
jedi-language-server: handler = self._get_handler(method_name)
jedi-language-server: File "/home/raoul/.local/lib/python3.7/site-packages/pygls/protocol.py", line 285, in _get_handler
jedi-language-server: raise JsonRpcMethodNotFound.of(feature_name)
jedi-language-server: pygls.exceptions.JsonRpcMethodNotFound
```
Just a little later the server requests the settings itself, this works fine:
```
:: <-- jedi-language-server workspace/configuration(81779ff2-e3d3-4040-89ce-57d1911b759e): {'items': [{'section': 'jedi', 'scopeUri': None}]}
:: >>> jedi-language-server 81779ff2-e3d3-4040-89ce-57d1911b759e: [{'diagnostics': {'didSave': True, 'didChange': True, 'didOpen': True, 'enabled': True}, 'completion': {'triggerCharacters': ['.']}, 'enabled': True, 'signnatureHelp': {'triggerCharacters': ['(', ',']}}]
```

**Comment by rwols** [comment]
My editor is SublimeText with the [LSP plugin](https://github.com/sublimelsp/LSP) by the way. I'm one of the maintainers.

It seems like there's a lot of confusion around workspace/didChangeConfiguration:

- vscode-eslint, vscode-json want this notification at startup, otherwise they won't do anything.
- Vetur (vue language server) does *not* want this notification, otherwise it'll crash.
- This framework does not like this notification either (in fact, it doesn't like any unknown notification, but that's another matter).

**Comment by danixeee** [comment]
Thanks for submitting, I'll take a look.

**Comment by mattn** [comment]
some issue on [vim-lsp](https://github.com/prabirshrestha/vim-lsp/) and [cmake-language-server](https://github.com/regen100/cmake-language-server) what use pygls.

**Comment by michaelaye** [comment]
Installed jedi-language-server today which pulled in pygls. Getting this error at startup. All packages up to date for a py38 conda-forge env.
pygls 0.9.1
