### ISSUE TITLE
TextDocumentSyncOptions not supported

### ISSUE THREAD

**Issue by polarmutex** [openlawlibrary/pygls#127]
textDocumentSync option can be a number (which pygls uses) or be of the form  of TextDocumentSyncOptions.  

I am working on a language server to interface with the native LSP client inside of neovim. The neovim client lsp implementation will not send didSave notifications unless "TextDocumentSyncOptions" is sent back. if a number is sent back only open, change, and close notifications are sent even if i define a didSave capability. 

Thoughts? I am new and just start started reading the LSP spec. and I might be missing something.

**Comment by danixeee** [comment]
Hi @bryall, we will need to add new types to `types.py` module and to rework logic for building `ServerCapabilities` response to support `TextDocumentSyncOptions`. You can fork the project and make those changes to the pygls on your end, but the end goal is to find a better way of how we create `ServerCapabilities`.

**Comment by danixeee** [comment]
Added in #139.

https://github.com/openlawlibrary/pygls/blob/master/pygls/lsp/types/text_synchronization.py#L40
