### ISSUE TITLE
context is optional in textDocument/completion

### ISSUE THREAD

**Issue by mattn** [openlawlibrary/pygls#128]
Current implementation does not deal with omitted context.

https://github.com/openlawlibrary/pygls/blob/e56b4be1e59720d4084cf82840ce46e3a2306b83/pygls/types.py#L1249

**Comment by rwols** [comment]
Related: https://github.com/openlawlibrary/pygls/issues/124

**Comment by danixeee** [comment]
Fixed in #139.

https://github.com/openlawlibrary/pygls/blob/master/pygls/lsp/types/language_features/completion.py#L91
