### ISSUE TITLE
Commands with argument inputs

### ISSUE THREAD

**Issue by TiemenSch** [openlawlibrary/pygls#134]
Some other (VS Code) extensions provide commands that can ask for additional user input (e.g. ``Developer: Show Logs...``).

Is this currently supported in ``pygls``? I can't seem to find any documentation on it. 

In terms of the JSON example: it might be instructional to add an additional countdown command with a ``user_input`` number of seconds.

**Comment by danixeee** [comment]
You can ask for additional user input on the client (VS Code) side and send the data to the server.

Take a look [here](https://github.com/textX/textX-LS/blob/master/client/src/services/projectService.ts#L152). 

You need to register an "internal" command that will call your client's function where you can make an interaction with the user and then call a server's command with the given input.

Is that something that you needed or I misunderstood?

**Comment by danixeee** [comment]
Closing this, let me know if you have additional questions.
