### ISSUE TITLE
Examples of using pygls

### ISSUE THREAD

**Issue by mike-vogel** [openlawlibrary/pygls#144]
Are there any other projects using pygls besides the json-extension that can be used to learn how to use other LSP features, e.g., Hover?

**Comment by krassowski** [comment]
Have a look at the [dependency graph](https://github.com/openlawlibrary/pygls/network/dependents); a few that stand out:
- https://github.com/pappasam/jedi-language-server
- https://github.com/muffinmad/anakin-language-server
- https://github.com/galaxyproject/galaxy-language-server/tree/master/server
- https://github.com/broadinstitute/wdl-ide
- https://github.com/textX/textX-LS/tree/master/textX-LS/server
- https://github.com/suoto/hdl_checker

**Comment by danixeee** [comment]
@krassowski Thanks for listing projects! The dependency graph no longer works for some reason, it might be related to `setup.cfg`, not sure.
