### ISSUE TITLE
Type of the id field in response message

### ISSUE THREAD

**Issue by muffinmad** [openlawlibrary/pygls#159]
The type of the `id` field in server response message is always `str` [now](https://github.com/openlawlibrary/pygls/blob/4d8d8e25fbedd3d41b75e8bfe041c99fe3611b1d/pygls/lsp/types/basic_structures.py#L72).

The LSP client can't get response for `{"id": 1, "method": "initialize}` request because pygls will respond with `{"id": "1", "result": {...}}` and `1 != "1"`. 

Can we please have the `id` in the response exactly the same as in the request?

**Comment by danixeee** [comment]
@muffinmad Although this was a bug in `pygls`, type checking for `Unions` is not working well in `pydantic`... I implemented some workaround for now.
