### ISSUE TITLE
Can psutil dependency be optional?

### ISSUE THREAD

**Issue by karthiknadig** [openlawlibrary/pygls#161]
We ship `jedi-language-server` with Python extension for VS Code, which depends on `pygls`. With the latest version `0.10.*` there is a dependency on `psutils` which means that we cant ship `jedi-language-server` in-box, since `psutil` needs the wheels on some platforms. Can the `psutil` dependency be made optional?

/cc @pappasam

**Comment by pappasam** [comment]
@karthiknadig possibly a silly question, but I'm just curious: how is the psutil dependency different (from an in-box shipping perspective) from our reliance on pydantic? Pydantic also ships compiled wheels:

- [pydantic](https://pypi.org/project/pydantic/#files)
- [psutil](https://pypi.org/project/psutil/#files)

**Comment by karthiknadig** [comment]
`psutil` requires wheels on osx and windows, some of the actual code they need is in C. Like this file for example
https://github.com/giampaolo/psutil/blob/master/psutil/_psutil_osx.c

It is not an issue with `pydantic`, because the wheels are there to provide optimizations, are not necessary.

On OSX we get this error if there are no wheels installed:
```
ImportError: cannot import name '_psutil_osx' from partially initialized module 'psutil' (most likely due to a circular import) (/Users/username/.vscode/extensions/ms-python.python-2021.4.680137574-dev/pythonFiles/lib/jedilsp/psutil/__init__.py)
```

**Comment by pappasam** [comment]
Understood. Looks like it's only in [1 place](https://github.com/openlawlibrary/pygls/blob/6cb9af98e67f4e71620c4ba1f0d0cd15757e8312/pygls/utils.py). @danixeee what are your thoughts about alternatives to psutil? It would be nice to remove as many 3rd party dependencies as possible from this foundational library.

**Comment by brettcannon** [comment]
@pappasam pydantic has a pure Python wheel (`py3-none-any`), so we can install and use that.

As for alternatives, I personally don't know of any. But looking at the code, could the use of psutil be optional?
```Python
try:  # CHANGED
    import psutil
except ImportError:
    psutil = None


async def process_watcher(pid, on_process_terminated, delay=5):
    """Periodically checks if the given pid exists.

    - pid: Process id to check
    - on_process_terminated: Function without arguments which is called if process is
                             not alive anymore
    - delay: Delay in seconds
    """
    while psutil:  # CHANGED
        if not psutil.pid_exists(pid):
            return on_process_terminated()
        await asyncio.sleep(delay)
```

**Comment by karthiknadig** [comment]
Additional note, monitoring `pid` directly like this does not guarantee that it is the client. `pid` could be recycled in the time between the two checks.

**Comment by perrinjerome** [comment]
Note that `psutil.pid_exists` is very simple ([code for reference](https://github.com/giampaolo/psutil/blob/bfae1fc4a371c9e08f2c3f5053a80542e43d18f7/psutil/_psposix.py#L34-L53)), it just uses `os.kill(pid, 0)`, which as described in [ kill(2) manpage](https://man7.org/linux/man-pages/man2/kill.2.html#:~:text=If%20sig%20is%200,%20then%20no%20signal%20is%20sent) :

>       If sig is 0, then no signal is sent, but existence and permission
>       checks are still performed; this can be used to check for the
>       existence of a process ID or process group ID that the caller is
>       permitted to signal.

I don't know how portable this is (anyway, it's what psutil does), but implementing this in pygls using `os.kill` from standard library looks another possibility.

**Comment by danixeee** [comment]
> how is the psutil dependency different (from an in-box shipping perspective) from our reliance on pydantic?

@pappasam Usually, platform-specific libs have multiple builds (for each platform). Take a look at https://pypi.org/project/psutil/5.8.0/#files. Or, if not, a needed platform-specific wheel is built on your machine when you run `pip install ...`.

 @perrinjerome I am not sure if we could just copy that function. Looks simple, but I guess it's somehow related to these C functions: [win](https://github.com/giampaolo/psutil/blob/master/psutil/_psutil_windows.c#L65), [posix](https://github.com/giampaolo/psutil/blob/master/psutil/_psutil_posix.c#L92). Look at comments on [SO answer](https://stackoverflow.com/a/568285/9669050).

The `process_watcher` function that I have added is needed only when the server is not run as a child-process of the client and that happens when you start it over TCP (`start_tcp`).

We could:

- try to copy `psutil` implementation and test if it works on major platforms
- make `psutil` an optional dependency and add log a warning message if the server is started over TCP without `psutil` being installed

Thoughts?

**Comment by brettcannon** [comment]
Totally ignorant question: if this is for the TCP scenario and not stdin/stdout scenario, would checking if the socket is not closed work?

**Comment by brettcannon** [comment]
And my (not important) vote is "make `psutil` an optional dependency" since cross-platform stuff is hard to maintain and it makes pygls the most useful on the most OSs (e.g. what if someone wants to run pygls on some "exotic" OS that you don't have support for?).

**Comment by brettcannon** [comment]
Actually, if this is **only** for the TCP situation (which I believe we don't use, right, @karthiknadig ?), then another solution is to still have psutil installed, but make the success or failure of the import contingent on a TCP server being started.

**Comment by danixeee** [comment]
> Totally ignorant question: if this is for the TCP scenario and not stdin/stdout scenario, would checking if the socket is not closed work?

@brettcannon Good point, I took a look at `asyncio.Protocol` and found a solution... I will create a PR now.

**Comment by karthiknadig** [comment]
@brettcannon That is correct we don't use TCP, we just use stdio.

**Comment by danixeee** [comment]
@karthiknadig, @pappasam, @perrinjerome, @brettcannon 

This should work #163.

**Comment by pappasam** [comment]
I'll be able to test out once I adding TCP support to `jedi-language-server` soon
