### ISSUE TITLE
test_tcp_connection_lost hangs under certain conditions

### ISSUE THREAD

**Issue by bollwyvl** [openlawlibrary/pygls#165]
Hi folks! Thanks again for pygls!

Downstream on [conda-forge](https://github.com/conda-forge/pygls-feedstock/pull/5), I'm trying to get `0.10.2` out... it looks like one of the tests fails if it can't bind to `0.0.0.0` under certain conditions (probably some docker nonsense, probably nobody's _fault_). Here are the [logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=296024&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=658). I'm skipping it for now :crossed_fingers: !

I'd wager it might just need to grab an unused port during the test... hopefully I can do some deeper looking and make a PR, but wanted to leave a note in case I forget!

**Comment by bollwyvl** [comment]
Can confirm that skipping that leaves everything else running :tada:!

**Comment by danixeee** [comment]
I googled it a bit and it looks like it's related to docker.

Try to change `localhost` to `127.0.0.1` in `test_tcp_connection_lost` and please submit a PR if that solves the issue. :)

**Comment by danixeee** [comment]
@bollwyvl Did you have time to try it out?

**Comment by bollwyvl** [comment]
Sorry not yet!

**Comment by bollwyvl** [comment]
Opened up #202 which seems to do the trick! Sorry for the delay!
