### ISSUE TITLE
Return unkown method "didChange" if unregistered document

### ISSUE THREAD

**Issue by suzizecat** [openlawlibrary/pygls#168]
Hi.

Using your examples in windows for VS Code, I came across the issue that, for whatever reason, a document I'm handling is not registered in `Workspace._docs`. 
The problem is that when receiving a "didChange" notification, the `bf_text_document__did_change` function call `workspace.update_document` which then raise a `KeyError`. 
This `KeyError` will be catched in the try/except block of `JsonRPCProtocol._handle_notification` and trigger the warning.
```text
Ignoring notification for unknown method "textDocument/didChange"
```

As the fact of my document not being registered is probably another problem that I'll investigate, this error is definitely misleading (and might be handled somehow ?)

Best regards.

**Comment by suzizecat** [comment]
The fact that my document was not registered came from a mistake on my end. I forgot that "starting" the server would mean having it block the rest of the script interpretation, thus avoiding the declaration of all bindings. (I had it just running right after its declaration).

PS : As I manipulate pygls a bit more, I got one thing to say : this stuff is awesome ! 🤩

**Comment by danixeee** [comment]
Great you figured it out, I wanted to take a look at this now, but I'll just close the issue then. :)

> PS : As I manipulate pygls a bit more, I got one thing to say : this stuff is awesome ! 🤩

Thank you!

**Comment by suzizecat** [comment]
To let you know, the actual issue (wrong diagnostic) might be worth fixing somehow.
Here the diagnostic should have been something along the lines of "tried didChange on a non-registered document".

**Comment by danixeee** [comment]
@suzizecat Could you link or write a code snippet that is causing this issue so I can better understand?

**Comment by suzizecat** [comment]
@danixeee Indeed !
Just take the server.py file from pygls tutorial (https://github.com/openlawlibrary/pygls/blob/master/examples/json-extension/server/server.py) and add something like
```python
json_server.start()
``` 
right bellow the `json_server` declaration, line 55.

Then, try to follow the tutorial and just write anything in the editor.

**Comment by danixeee** [comment]
Yes, that's blocking, so all lines below won't be processed.
Every open document **must** be registered in the pygls workspace, so "tried didChange on a non-registered document" should never happen actually.

I guess we could have better error messages at some places, but not sure if we can cover all the possible cases. :)

**Comment by suzizecat** [comment]
That might be quite hard to get all cases covered 😅 
My point was only that you might want to cover this one since I found the point where you could add a raise clause.
Actually adding it is up to you guys if you think it can bring any added value.
