### ISSUE TITLE
Progress report capabilities

### ISSUE THREAD

**Issue by suzizecat** [openlawlibrary/pygls#170]
Hi there,

I am trying to setup a progress report from the LS to Visual Code.

I implemented the following functions :

```python
@diplomat_server.command(DiplomatLanguageServer.CMD_TST_PROGRESS_STRT)
def on_start_progress(ls : DiplomatLanguageServer, *args):
	initiate_progress(ls)
	print("Start progress on uuid",ls.progress_uuid)
	ls.send_notification("$/progress",WorkDoneProgressParams(token=ls.progress_uuid,value=WorkDoneProgressBegin(title = "Working hard")))


@diplomat_server.command(DiplomatLanguageServer.CMD_TST_PROGRESS_STOP)
def on_stop_progress(ls : DiplomatLanguageServer, *args):
	print("Stop progress")

	ls.send_notification("$/progress",WorkDoneProgressParams(token=ls.progress_uuid, value=WorkDoneProgressEnd(message = "Stuff done.")))

@diplomat_server.command(WINDOW_WORK_DONE_PROGRESS_CREATE)
def initiate_progress(ls : DiplomatLanguageServer, *args) -> ProgressToken:
	ls.progress_uuid = uuid.uuid4().int
	return ls.progress_uuid
```

When I execute `on_start_progress` and `on_stop_progress` from a client command, I do get the appropriates prints on the python side, however, I have no reaction at all even though I expect to have an indefinite progress bar.

I haven't found any resource about this in the documentation so is there a limitation that I'm not aware of or an obvious mistake 
? I suspect my `initiate_progress` command or its call are the problem, but I have no clue about how to do otherwise...

If there is a place to  ask for help which is more appropriate than GH issues, please let me know. 

Best regards,
Julien Faucher

**Comment by danixeee** [comment]
@suzizecat I haven't tried this yet.

Take a look at the [specs](https://microsoft.github.io/language-server-protocol/specification#initiatingWorkDoneProgress). [This](https://microsoft.github.io/language-server-protocol/specification#serverInitiatedProgress) says that if you want to initiate a progress server-side, you need to send a request to the client first, and, if it is successful, you can report changes with notification `$/progress`.

This is new LSP stuff, which is not added to the `pygls` yet. However, you can try this in the meantime:

```python
import uuid
from asyncio import sleep
from pygls.lsp import (WINDOW_WORK_DONE_PROGRESS_CREATE, Model,
                       WorkDoneProgressBegin, WorkDoneProgressCreateParams,
                       WorkDoneProgressEnd, WorkDoneProgressParams,
                       WorkDoneProgressReport)

# Add this until we update pygls models
class ProgressParams(Model):
    token: ProgressToken
    value: Any


@json_server.command("SHOW_PROGRESS")
async def on_progress_show(ls: DiplomatLanguageServer, *args):
   progress_token = uuid.uuid4().int

    # Tell the client to create a progress bar
    await ls.lsp.send_request_async(
        WINDOW_WORK_DONE_PROGRESS_CREATE,
        WorkDoneProgressCreateParams(
            token=progress_token
        )
    )

    # Begin
    ls.send_notification(
        '$/progress',
        ProgressParams(
            token=progress_token,
            value=WorkDoneProgressBegin(
                kind='begin',   # <- for some reason you need to pass "kind" (this is a serialization issue that needs to be addressed)
                title='Begin',
                percentage=0
            )
        )
    )

    for i in range(1, 10):
        ls.send_notification(
            '$/progress',
            ProgressParams(
                token=progress_token,
                value=WorkDoneProgressReport(
                    kind='report',
                    message=f'Message {i}',
                    percentage= i * 10
                )
            )
        )

        await sleep(2)


    ls.send_notification(
        '$/progress',
        ProgressParams(
            token=progress_token,
            value=WorkDoneProgressEnd(
                kind='end',
                message='End',
            )
        )
    )
```

NOTE: Be sure to update VS Code related npm packages.

**Comment by perrinjerome** [comment]
Also, that's just a random guess, but I see `print` statements in the code you posted. When running the server in stdio mode, you should not be printing on stdout, otherwise the print statements output get mixed up in the protocol output and the messages are no longer valid.

**Comment by suzizecat** [comment]
@danixeee Thanks for the example. It works well on my side so I will be able to make it work in my situation.
Just to confirm, if  want to use a thread instead of a coroutine should I use `ls.lsp.send_request` ? I didn't found such function in some documentation.

@perrinjerome Thanks for the head-up. I'm currently running my server in tcp mode so no issue yet. I'll keep this in mind when switching to stdio mode.

**Comment by danixeee** [comment]
We will add some helper methods to the server class, like `get_configuration` and `get_configuration_async`.

You can see differences between _thread_, _async_, and _callback_ approaches in the [json example](https://github.com/openlawlibrary/pygls/blob/master/examples/json-extension/server/server.py).

In your case: 

```python
@server.thread()
@server.command("SHOW_PROGRESS")
def on_progress_show(ls: DiplomatLanguageServer, *args):
   progress_token = uuid.uuid4().int

    # Tell the client to create a progress bar
    ls.lsp.send_request(
        WINDOW_WORK_DONE_PROGRESS_CREATE,
        WorkDoneProgressCreateParams(
            token=progress_token
        )
    ).result(1) # waits for 1 second before raise the exception

    ...
```

**Comment by danixeee** [comment]
@suzizecat [Progress reporting](https://github.com/openlawlibrary/pygls/blob/master/examples/json-extension/server/server.py#L155) is now added to the server.
