### ISSUE TITLE
textDocument/completion feature not working properly

### ISSUE THREAD

**Issue by misdocumeno** [openlawlibrary/pygls#171]
the `completions` function is called on every change in the document, regardless of the `trigger_characters` list sent inside the `CompletionOptions` object to the `ls.feature(...)` decorator

**Comment by danixeee** [comment]
I can't reproduce this, but the client is the one who is triggering everything. Try updating VS Code and client npm packages and let me know if that solves the issue.

**Comment by misdocumeno** [comment]
**what I did:**

- I update vscode to the latest version (it was already up to date)

- I downloaded [this](https://github.com/microsoft/vscode-extension-samples/tree/63d86e3a0e459b2adf26487204891f7af62898ce/lsp-sample) example from the microsoft repo

I kept much of it unmodified, except the server obviously, I replaced it with a python virtual environment

```
python -m venv env
./env/Scripts/Activate.ps1
python -m pip install pygls
```

everything fine so far

- I did `npm i` inside the root folder


the extension development host works as expected, the server with pygls starts fine, no errors, the only problem (so far) is completions being called every time a character is inserted

[my entire folder](https://drive.google.com/file/d/11_PyNxSPxOwGiCQWwQQiVi2sThR5X4F-) just in case, idk whats the problem (with the python virtual environment included, windows)
just do `npm i` and create a `.sp` file in the extension development host

**Comment by danixeee** [comment]
Could you first try our [json-extension example](https://github.com/openlawlibrary/pygls/tree/master/examples/json-extension) and let me know if you have the same issue?

**Comment by misdocumeno** [comment]
- I copied everything from the json example

```
python -m venv env (python 3.8.5)
.\env\Scripts\Activate.ps1
python -m pip install pygls (pip 20.1.1)
npm i (npm 7.6.3)
```

and i get this:
```
> json-extension@0.10.2 postinstall
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.22.0
Error installing vscode.d.ts: Error: Request returned status code: 404
Details: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/releases/stable</pre>
</body>
</html>

npm ERR! code 1
npm ERR! path D:\Documentos\jsonextensiontest
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./node_modules/vscode/bin/install

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mis\AppData\Local\npm-cache\_logs\2021-04-17T16_37_45_843Z-debug.log
```
[2021-04-17T16_37_45_843Z-debug.log](https://pastebin.com/CUZLiSLy)

thats why I tried using the microsoft lsp-server example, and replacing the server with a python environment and pygls

**Comment by danixeee** [comment]
I just updated npm packages in the `json-extension` example in #175. Please checkout `danixeee/json-example-npm-updates` and try again.

Here's my output:

```
Daniels-MBP:json-extension daniel$ node --version
v14.15.1
Daniels-MBP:json-extension daniel$ npm --version
7.10.0
Daniels-MBP:json-extension daniel$ npm i

added 174 packages, and audited 175 packages in 2s

found 0 vulnerabilities
```

For the server, as you already know, you need to create a new python virtual env, install `pygls`, and add a python path to the `settings.json`:

```json
{
    "python.pythonPath": "......../bin/python",
}
```

After that, just open `json-extension` in a new VS Code window or add it as a workspace folder, and start debugging (`Server + Client`).

Let me know if `completions` are working well.

**Comment by misdocumeno** [comment]
seems to be working fine now, thanks for the help
