### ISSUE TITLE
Move from Azure Pipelines to GitHub Actions

### ISSUE THREAD

**Issue by brettcannon** [openlawlibrary/pygls#172]
Any interest in moving to GitHub Actions? I noticed the Actions tab is turned on in this repo but isn't being used. I'm willing to do the work to set it up if you're interested.

**Comment by danixeee** [comment]
Is there any important difference? Anyway, I don't mind.

@dgreisen Any thoughts?

**Comment by brettcannon** [comment]
GitHub Actions is faster and there is way more institutional knowledge from folks in the community compared to Azure Pipelines.

**Comment by dgreisen** [comment]
I believe the primary reason we went with Azure was so we could test on windows and linux. It [appears](https://github.com/features/actions) we can do all that and more with actions. So I'm fine with actions.

**Comment by brettcannon** [comment]
GitHub Actions covers Windows, Linux, and macOS.

**Comment by danixeee** [comment]
Correct, we wanted to test it on both Windows and Linux platforms. @brettcannon If you are still willing to make the transition to GitHub actions, please feel free to do it.

**Comment by brettcannon** [comment]
Yep, I am still up to do it, just don't have an exact ETA.

Any changes you would want, like testing against Python 3.9?

**Comment by danixeee** [comment]
Sure. So, we would test it for python 3.6-3.9 on all three major platforms?

**Comment by brettcannon** [comment]
You tell me. 😄 In a lot of projects I see them avoid using macOS simply because it has the greatest chance of holding up results and it often isn't different enough to Linux for Unix-like testing (drawback of Apple not letting people install macOS on anything but a Mac; have to have a literal rack of Mac machines to provide the service).

**Comment by danixeee** [comment]
Makes sense, but I didn't notice any issues with the [macOS builds](https://github.com/textX/textX-LS/runs/1288835004) for another project. We run tests on win32, win64, macOS, and Linux platforms there just fine, but I agree with you that it's maybe not needed. You can just transition what we have now (+python 3.9) and we could always change it later :)

**Comment by brettcannon** [comment]
I've hit a snag. In the Azure  Pipelines definition you are checking the JSON extension using `tslint`:

https://github.com/openlawlibrary/pygls/blob/11096f7b4d9527a41130021aae03f9a4f66fec4b/azure-pipelines.yml#L59

But what you're in fact installing is eslint:

https://github.com/openlawlibrary/pygls/blob/11096f7b4d9527a41130021aae03f9a4f66fec4b/examples/json-extension/package.json#L72

The problem is that [eslint wants a configuration file](https://github.com/brettcannon/pygls/runs/2424186110?check_suite_focus=true#step:7:9), so running it fails. How would you like me to handle this?

I also can't turn on Python 3.9 support with this work as mypy fails. I'll leave that as a separate thing.

And if you're curious how this looks so far, see https://github.com/brettcannon/pygls/actions.

**Comment by brettcannon** [comment]
FYI I found out the 3.9 failure is due to mypy being pinned to an old version. I'll worry about fixing it once I found out what you want to do about about eslint and get GitHub Actions working.

**Comment by danixeee** [comment]
I removed `tslint` in #175, but forgot to update pipelines yaml.

> The problem is that eslint wants a configuration file, so running it fails. How would you like me to handle this?

Could you please add a configuration file? Use whatever configuration you like.

> FYI I found out the 3.9 failure is due to mypy being pinned to an old version. I'll worry about fixing it once I found out what you want to do about eslint and get GitHub Actions working.

I noticed the same issue in #157 where mypy was updated to the latest version. We should probably fix/merge #157 first. I can do that, so you can continue with your PR.

**Comment by brettcannon** [comment]
I'm fine with waiting for #157 to be merged before worrying about any PR from me (especially since I asked a question on #157 which might lead to me making another PR 😉 ).

**Comment by brettcannon** [comment]
Got it all working (https://github.com/brettcannon/pygls/actions)! Just let me know when #157 has been merged and then I can do a merge against the default branch and create a PR.

**Comment by danixeee** [comment]
@brettcannon #157 is merged now, please go ahead and make a PR when you can.
