### ISSUE TITLE
Cannot run the json-extension example

### ISSUE THREAD

**Issue by limdauto** [openlawlibrary/pygls#193]
Hi, 

I'm trying to run the JSON extension example. I tried to follow the README but couldn't get it working. Generally, what I was doing was:

* Launch a server manually (either through Launch configuration or just plainly through the command line). I could verify that the server is running on port 2087.
* Launch the client through the Launch configuration.

However, whenever I try to execute a command, it keeps saying the command is not found. Do you have any recommendation how I could debug this?

**Comment by limdauto** [comment]
Closing because even though I still haven't been able to run the JSON example, I can run the minimal server example instead.

**Comment by danixeee** [comment]
@limdauto I just cloned a fresh repo and install everything from scratch and I can't reproduce the issue.

Which version of npm and node do you have? I am testing with `npm 6.14.13` and `node v14.15.1`.

**Comment by DeeeeLAN** [comment]
I am seeing the same issue, I don't think it makes sense to close the ticket. I am running `npm 6.14.15` and `node v14.17.6`. I cloned the repo, set up the venv, installed the npm dependencies, launched the server + client debug profile, opened a json file, and added a breakpoint to `completions`. When I hit `ctrl+space` in the client json file, the menu pops up without triggering the breakpoint. When I open the command menu and select `Count down 10 seconds [Blocking]`, It pops up an error: 

![image](https://user-images.githubusercontent.com/12877032/131720694-22639862-46e9-43ce-a74e-9e45ae402b0c.png)

**Comment by DeeeeLAN** [comment]
I just realized my issue is probably because I am running it over remote-ssh, although forwarding the debug port doesn't immediately resolve the issue.

**Comment by DeeeeLAN** [comment]
Digging into this more, for whatever reason, even though I have my python path set up to point to a 3.6.8 version of python and I can see it being called in the command when I launch the debug tasks, the client output states the python server failed and shows it attempted to use a 2.7 executable. I am not sure where it is getting that path.

**Comment by DeeeeLAN** [comment]
I have traced my particular issue to the client not picking up the `VSCODE_DEBUG_MODE` setting in the launch configuration, maybe because it is connecting over remote-ssh to an already running server instance. I don't know. Anyway, when I hard-code the `isStartedInDebugMode()` to true, the server connects properly. The client was attempting to launch the server on it's own and was selecting the python2 path since the VS Code python extension doesn't use `pythonPath` anymore.

**Comment by davelopez** [comment]
Hi @DeeeeLAN, you can use the [ExtensionContext.extensionMode](https://code.visualstudio.com/api/references/vscode-api#ExtensionMode) to check if you are running in debug mode (Development).

It would be something like this:
````js
export async function activate(context: ExtensionContext) {
    if (context.extensionMode === ExtensionMode.Development) {
        // Development mode
    } else {
        // Production or Test mode
    }
}
````

**Comment by danixeee** [comment]
@DeeeeLAN Included example shows how to use pygls SDK and it is working well if you follow steps from [Readme](https://github.com/openlawlibrary/pygls/tree/master/examples/json-extension#json-language-server).

You can try what @davelopez suggested above and if it is working for you, please create a PR to replace `isStartedInDebugMode()`.

**Comment by DeeeeLAN** [comment]
Thanks, that appeared to work great.
