### ISSUE TITLE
Completion provider to provide non-saved file contents

### ISSUE THREAD

**Issue by mturoci** [openlawlibrary/pygls#194]
Hi, great work on the lib!

I am writing a VSC extension for our python framework and trying to implement autocomplete. The problem is `trigger_characters` are not enough for me as I would need to know more context. E.g. differentiate when the completion was triggered by `q.client.` or `q.app.` so that I could provide valid completion items ofc. I am able to get the triggering file contents, but it is not up to date as the file is dirty (not saved yet).

My question is if there is any way to get the file contents of a dirty file.

**Comment by danixeee** [comment]
Hey, thanks.

Text document synchronization is done before calling other features like `code completion`. You can get a (dirty) file content like this:

```python
@json_server.feature(COMPLETION, CompletionOptions(trigger_characters=[',']))
def completions(ls: JsonLanguageServer, params: Optional[CompletionParams] = None) -> CompletionList:
    """Returns completion items."""
    text_doc = ls.workspace.get_document(params.text_document.uri) # `text_doc.source` will return a string content
    cursor_pos = params.position
    
    if params.context:
        trigger_kind = params.context.trigger_kind
        trigger_ch = params.context.trigger_character

    # your logic here
```

What is `q.client` and `q.app`?

Hope this helps.

**Comment by mturoci** [comment]
Thanks for response @danixeee, unfortunately, this doesn't give me dirty file contents like I need. See the demo:

https://user-images.githubusercontent.com/64769322/122000461-247bdc00-cdaf-11eb-84e8-ef8e7cbd135d.mov

I only get the file contents that was previously saved (notice the missing `q` in `text_doc.source`).
![image](https://user-images.githubusercontent.com/64769322/122000902-d2878600-cdaf-11eb-9095-2561162fc8e3.png)


Another weird thing is that completion is triggered even when writing `q` (without `.`) which seems like should not be the case since `trigger_characters` have `'.'` specified).

> What is q.client and q.app?

Nothing fancy, just a python object for storing various state of our framework.

**Comment by danixeee** [comment]
> Another weird thing is that completion is triggered even when writing q (without .) which seems like should not be the case since trigger_characters have '.' specified).

Ok, this is true, but I don't know why... :) Even if it's triggered, a list of completions on the client is not displayed unless the trigger characters are not matched.

Can you check the JSON server example in this project? File content stored in the server's memory matches the one on the client even if it's not saved (`save` doesn't do anything by default in `pygls`).

**Comment by mturoci** [comment]
> File content stored in the server's memory matches the one on the client even if it's not saved 

You are right, this works as expected. This implied I have a bug in my code, but then I managed to repro in your example project as well. Simply remove `did_open`, `did_change` and `did_close` and you should get the behavior I described. I guess this is not expected.

This also clarifies why my original code didn't work - I removed all the unnecessary boilerplate.

So basically I am able to workaround, but I guess this is not really expected behavior. Maybe I am missing something?

**Comment by danixeee** [comment]
A great catch actually! Can you see if #195 works for you? I am still not sure why is `code completion` called on _every_ character.

**Comment by mturoci** [comment]
@danixeee I can confirm that proposed fix works like a charm for me, thanks!

**Comment by mturoci** [comment]
@danixeee unfortunately, this issues will probably need to be reopened. It seems like it was fixed for dev build, but when I bundle the extension into `.vsix` I face it again.

Using empty `did_open`, `did_change` and `did_close` as a workaround.

**Comment by danixeee** [comment]
@mturoci Could you send the content of a log file?
