### ISSUE TITLE
Any example on how to use semantic tokens?

### ISSUE THREAD

**Issue by kalsky** [openlawlibrary/pygls#204]

**Comment by kalsky** [comment]
When I try to use
@server.feature(TEXT_DOCUMENT_SEMANTIC_TOKENS)
I see in the logs that it registers it as a provider, but nothing gets to this function.

When I try to use
@server.feature(TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL) 
or any of the other 2 options, I don't see that it's getting registered as server capabilities.

Can you provide an example of how to make it work?

**Comment by alcarney** [comment]
I've had a play around with the example json language server in this repo and I've managed to get something to work, though it appears that there may be a bug or two in `pygls`. Here is the result with semantic tokens

![image](https://user-images.githubusercontent.com/2675694/133476635-385babe8-ed87-4566-8c43-c1a5e23de44b.png)

vs the result without

![image](https://user-images.githubusercontent.com/2675694/133476918-ee92cfa5-c3f4-4dc9-9aa6-ccda1fcd5e0c.png)

In the [json-extension](https://github.com/openlawlibrary/pygls/blob/master/examples/json-extension/server/server.py) example server code I added the following, hardcoded to work with the `test.json` file in the screenshots above
```python
@json_server.feature(
    TEXT_DOCUMENT_SEMANTIC_TOKENS,
    SemanticTokensOptions(
        legend=SemanticTokensLegend(
            tokenTypes=["class", "keyword"],
            tokenModifiers=[]
        )
    )
)
def semantic_tokens(ls):
    """Used to signal to the client that we support semantic tokens."""

@json_server.feature(
    TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL
)
def semantic_tokens_full(ls, params: SemanticTokensParams):
    """A 'full' semantic tokens request."""

    return SemanticTokens(data=[
        0, 1, 7, 1, 0,
        0, 9, 5, 0, 0,
        0, 6, 6, 1, 0,
        0, 8, 8, 0, 0
    ])
```
Here's a quick breakdown of the above
- Tokens are sent to the client as a long list of numbers, each group of 5 numbers describe a single token.
  - The first 3 numbers describe the token's line number, character index and length, relative to the previous token
  - The final 2 numbers specify the type of token, the client uses them to index into the arrays given in the `SemanticTokenLengend` see the [LSP Specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_semanticTokens) for full details

**Comment by alcarney** [comment]
There does however, seem to be a few bugs in how `pygls` fills out the `ServerCapabilities` field for semantic tokens so in order to make the example above work, I had to make the following changes in `pygls` itself.

```diff
diff --git a/pygls/capabilities.py b/pygls/capabilities.py
index c7191dd..7165d57 100644
--- a/pygls/capabilities.py
+++ b/pygls/capabilities.py
@@ -22,7 +22,7 @@ from pygls.lsp.methods import (CODE_ACTION, CODE_LENS, COMPLETION, DECLARATION,
                                TEXT_DOCUMENT_CALL_HIERARCHY_PREPARE, TEXT_DOCUMENT_DID_CLOSE,
                                TEXT_DOCUMENT_DID_OPEN, TEXT_DOCUMENT_DID_SAVE,
                                TEXT_DOCUMENT_LINKED_EDITING_RANGE, TEXT_DOCUMENT_MONIKER,
-                               TEXT_DOCUMENT_SEMANTIC_TOKENS, TEXT_DOCUMENT_WILL_SAVE,
+                               TEXT_DOCUMENT_SEMANTIC_TOKENS, TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL, TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL_DELTA, TEXT_DOCUMENT_SEMANTIC_TOKENS_RANGE, TEXT_DOCUMENT_WILL_SAVE,
                                TEXT_DOCUMENT_WILL_SAVE_WAIT_UNTIL, TYPE_DEFINITION,
                                WORKSPACE_DID_CREATE_FILES, WORKSPACE_DID_DELETE_FILES,
                                WORKSPACE_DID_RENAME_FILES, WORKSPACE_SYMBOL,
@@ -237,6 +237,13 @@ class ServerCapabilitiesBuilder:
                                            ),
                                        ))
         if value is not None:
+            value.range = TEXT_DOCUMENT_SEMANTIC_TOKENS_RANGE in self.features
+            
+            if TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL_DELTA in self.features:
+                value.full = {"delta": True}
+            else:
+                value.full = TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL in self.features
+            
             self.server_cap.semantic_tokens_provider = value
         return self
 
diff --git a/pygls/lsp/__init__.py b/pygls/lsp/__init__.py
index 905f830..9405f53 100644
--- a/pygls/lsp/__init__.py
+++ b/pygls/lsp/__init__.py
@@ -107,6 +107,11 @@ LSP_METHODS_MAP = {
         MonikerParams,
         Optional[List[Moniker]],
     ),
+    TEXT_DOCUMENT_SEMANTIC_TOKENS: (
+        Union[SemanticTokensOptions, SemanticTokensRegistrationOptions],
+        SemanticTokensParams,
+        Union[SemanticTokensPartialResult, Optional[SemanticTokens]],
+    ),
     TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL: (
         Union[SemanticTokensOptions, SemanticTokensRegistrationOptions],
         SemanticTokensParams,


```

I'm not entirely sure however, if the example above is how `pygls` intends the semantic tokens feature to be used but I'm happy to open a PR with these changes if that would be useful :smile:

**Comment by Lorac** [comment]
@alcarney It would be helpful to me as I got the same missing feature when trying to use it. I think it's from 3.16 LSP, so I don't know if it will require something special additional to modify.

**Comment by tombh** [comment]
Did #213 fix this? Or where are we with this?

**Comment by alcarney** [comment]
The json-extension now includes an [example](https://github.com/openlawlibrary/pygls/blob/master/examples/json-extension/server/server.py#L163) on semantic tokens, so it's probably safe to close this.

**Comment by tombh** [comment]
Oh right, great, thanks.
