### ISSUE TITLE
Is there an example that I can see for Progress API?

### ISSUE THREAD

**Issue by karthiknadig** [openlawlibrary/pygls#225]
I made a few attempts to get the progress API working on one of my projects. I have not been able to get it to work right. Is there any example or implementation I can look at for this?

**Comment by alcarney** [comment]
I think the progress API is used in the example [json-extension](https://github.com/openlawlibrary/pygls/blob/master/examples/json-extension/server/server.py#L198-L214) - does that help?

**Comment by karthiknadig** [comment]
That helps, Thanks!!!
