### ISSUE TITLE
[BUG] location of `data_files` breaks type checking when using a virtual environment

### ISSUE THREAD

**Issue by ITProKyle** [openlawlibrary/pygls#232]
> **NOTE:** This has only been tested with pyright as the type checker and a virtual environment created by poetry. It could be isolated to this combination of tools or it may affect other.

When type checking my project with `pygls` installed, `pyright` is unable to import dependencies. Example from running `npx pyright --venv-path ./ --verbose`

```
Could not import 'pydantic' in file '/path/to/project/project/utils/__init__.py'
  Looking in stubPath '/path/to/project/typings'
  Attempting to resolve stub package using root path '/path/to/project/typings'
  Attempting to resolve using root path '/path/to/project/typings'
  Looking in root directory of execution environment '/path/to/project'
  Attempting to resolve stub package using root path '/path/to/project'
  Attempting to resolve using root path '/path/to/project'
  Looking in python search path '/path/to/project/.venv/lib/site-packages'
  Attempting to resolve stub package using root path '/path/to/project/.venv/lib/site-packages'
  Attempting to resolve using root path '/path/to/project/.venv/lib/site-packages'
  Looking for typeshed stdlib path
  Looking for typeshed stdlib path
  Attempting to resolve using root path '/path/to/project/node_modules/pyright/dist/typeshed-fallback/stdlib'
  Typeshed path not found
  Looking for typeshed third-party path
  Looking for typeshed stubs path
  Typeshed path not found
```

Notable in this output is the search path `.venv/lib/site-packages` which only contains data files for `pygls`.  The correct path for dependencies within this virtual environment is `.venv/lib/python3.10/site-packages`.

![image](https://user-images.githubusercontent.com/23145462/168603601-bdde2a53-b991-44b5-bd23-f1a0c0d98673.png)

I believe the existence of `.venv/lib/site-packages` causes the correct path to not be used. Removal of `pygls` as a dependency resolves this issue as `.venv/lib/site-packages` is no longer created.

Here is the section of code causing `.venv/lib/site-packages` to be created: https://github.com/openlawlibrary/pygls/blob/75c9b1556132a984719f048f147fe0dcbdb837aa/setup.cfg#L53-L56

---

I am using the following packages/tools:

- multiple versions of python used to test this
  - python3.10 (installed via homebrew)
  - python3.9 (installed via pyenv)
  - python3.8 (installed via pyenv)
- `poetry==1.1.13` used to manage dependencies and create a virtual environment
- `pygls==0.11.3` (installed as a dependency of `esbonio==0.11.2`)
- `pyright@1.1.246`

**Comment by tombh** [comment]
Apologies for such a late reply. I've been considering moving Pygls over to using Poetry. I suspect that would fix this issue?
