### ISSUE TITLE
Reference VSCode extension for Pygls servers and suggest starting points for other editors 

### ISSUE THREAD

**Issue by tombh** [openlawlibrary/pygls#281]
Microsoft maintains a VSCode extension template: https://github.com/microsoft/vscode-python-tools-extension-template I think it should be made prominent in our README and docs as the recommended way for Pygls servers to support VSCode.

We should also provide recommended configs for other editors. Esbonio has good examples: https://swyddfa.github.io/esbonio/docs/latest/en/lsp/getting-started.html

These should also be added to Implementations.md if @karthiknadig and @omnilib agree?:

* https://github.com/microsoft/vscode-isort
* https://github.com/microsoft/vscode-black-formatter
* https://github.com/microsoft/vscode-pylint
* https://github.com/microsoft/vscode-autopep8
* https://github.com/microsoft/vscode-flake8
* https://github.com/omnilib/vscode-ufmt

**Comment by tombh** [comment]
@karthiknadig, @omnilib, @brettcannon: any thoughts on this?

**Comment by brettcannon** [comment]
It's totally fine by us!

**Comment by brettcannon** [comment]
You can also add https://github.com/microsoft/vscode-isort/ to that list.

**Comment by tombh** [comment]
Great, thanks!

**Comment by charliermarsh** [comment]
Of course, happy to be included!

**Comment by tombh** [comment]
Thanks @charliermarsh!
