### ISSUE TITLE
Pygls is corrupting custom messages.

### ISSUE THREAD

**Issue by alcarney** [openlawlibrary/pygls#285]
**This is an issue for the unreleased 1.0 branch** (see #273)

`esbonio` sends a custom notification to the client after each completed Sphinx build. The notification `params` field is a custom object with fields that the client might find useful
```
[client] Build complete {
  "config": {
    "sphinx": {
      "buildDir": "/var/home/alex/Projects/esbonio-pygls/docs/_build/html",
      "confDir": "/var/home/alex/Projects/esbonio-pygls/docs",
      "doctreeDir": "/var/home/alex/Projects/esbonio-pygls/docs/_build/doctrees",
      "srcDir": "/var/home/alex/Projects/esbonio-pygls/docs",
      "command": [
        "sphinx-build",
        "-M",
        "html",
        "/var/home/alex/Projects/esbonio-pygls/docs",
        "/var/home/alex/Projects/esbonio-pygls/docs/_build/html",
        "-d",
        "/var/home/alex/Projects/esbonio-pygls/docs/_build/doctrees"
      ],
      "version": "5.3.0"
    },
    "server": {
      "logLevel": "debug"
    }
  },
  "error": false,
  "warnings": 0
}
```
However while trying the v1.0 branch that same notification comes through in the following format.

```
[client] Build complete [
  [
    "/var/home/alex/Projects/esbonio-pygls/docs/_build/html",
    "/var/home/alex/Projects/esbonio-pygls/docs",
    "/var/home/alex/Projects/esbonio-pygls/docs/_build/doctrees",
    "/var/home/alex/Projects/esbonio-pygls/docs",
    [
      "sphinx-build",
      "-M",
      "html",
      "/var/home/alex/Projects/esbonio-pygls/docs",
      "/var/home/alex/Projects/esbonio-pygls/docs/_build/html",
      "-d",
      "/var/home/alex/Projects/esbonio-pygls/docs/_build/doctrees"
    ],
    "5.3.0"
  ],
  [
    "debug"
  ]
]
```
I found the culprit and it's due to the definition of the generic `JsonRpcNotification` type, in particular the `dict_to_object` converter on the `params` field.

```python
@attrs.define
class JsonRPCNotification:
    """A class that represents a generic json rpc notification message.
    Used as a fallback for unknown types.
    """

    method: str
    jsonrpc: str
    params: Any = attrs.field(converter=dict_to_object)
```
A bit of context.

Currently when pygls ecounters a message it does not recognise, it calls `dict_to_object` on it so that you can still use `params.obj.field` syntax to access values stored in what would otherwise be a raw `dict`.

Unfortunately, setting `dict_to_object` as a `converter` on this field means it's also called on any messages the server creates, corrupting them when they are serialized (though I have no idea why that is).  Removing this converter fixes the issue seen in `esbonio`. 

I guess I have a couple of questions 
- Do we want to try and preserve pygls' original behavior? Or should we remove `dict_to_object` entirely and call it a breaking change.
- @karthiknadig, assuming we decide to try and preserve the behavior, do you think a custom structure hook would let us call `dict_to_object` on incoming messages, while leaving the outgoing ones unchanged?

**Comment by karthiknadig** [comment]
I think you can do this by using a hook for `JsonRPCNotification` registered via `cattrs` than using a converter is `attrs.field`. See, `_hooks.py` in `lsprotocol` for examples.

**Comment by tombh** [comment]
I don't full understand the details of this issue. But either way it sounds like we need to make a change in Pygls before merging v1? The question is whether it can be done without a breaking change or not?
