### ISSUE TITLE
Provide a mechanism to set a custom converter

### ISSUE THREAD

**Issue by alcarney** [openlawlibrary/pygls#286]
**This is an issue for the unreleased 1.0 branch** (see #273)

pygls' is essentially hardcoded to use the converter as provided by `lsprotocol` since it uses one defined in the [module's scope](https://github.com/openlawlibrary/pygls/blob/7c06b314d374e1d1f56c5c80c3fd08d289980196/pygls/protocol.py#L72). If a server defines its own types, chances are it will want to provide a customized converter with its own structure hooks etc.

Instead the `Server` class should probably accept a `converter_factory` keyword argument which it can call to obtain a converter that it can then pass to the protocol class [when it creates an instance of it](https://github.com/openlawlibrary/pygls/blob/7c06b314d374e1d1f56c5c80c3fd08d289980196/pygls/server.py#L197)

**Comment by tombh** [comment]
Is this your solution to #285?

Would the `converter_factory` need to inherit from `lsprotocol.converters.get_converter()`?

**Comment by alcarney** [comment]
> Is this your solution to https://github.com/openlawlibrary/pygls/issues/285?

No, #285 is about fixing pygls’ fallback type definitions so it can still function when it encounters unknown message types.

This one is more about teaching pygls to recognise custom messages by passing it a converter that knows how to handle them.

> Would the converter_factory need to inherit from lsprotocol.converters.get_converter()

Not in the sense of subclassing, but you would need to make sure your custom factory bases itself on the result of the one provided by `lsprotocol` e.g.

```python
from lsprotocol.converters import get_converter

def my_converter_factory():
    converter = get_converter()
    converter.register_structure_hook(MyCustomType, hook_func)

    return converter
```

**Comment by tombh** [comment]
Ahh right. So there's 3 things:
1. The formal LSP protocol itself
2. Explicitly defined custom additions to the formal protocol (this issue)
3. The formatting of anything that isn't covered by 1 and 2 (#285)
