### ISSUE TITLE
Inconsistent date formats in changelog

### ISSUE THREAD

**Issue by perrinjerome** [openlawlibrary/pygls#300]
Recent entries are in D/MM/YYYY format:

https://github.com/openlawlibrary/pygls/blob/24fe1f080995b8af592964f9f81866bac93bac34/CHANGELOG.md?plain=1#L13

Older entries were in MM/DD/YYYY format

https://github.com/openlawlibrary/pygls/blob/24fe1f080995b8af592964f9f81866bac93bac34/CHANGELOG.md?plain=1#L306

From CHANGELOG.md:

https://github.com/openlawlibrary/pygls/blob/24fe1f080995b8af592964f9f81866bac93bac34/CHANGELOG.md?plain=1#L5

 [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) recommends YYYY-MM-DD format.

> ## Confusing Dates
> Regional date formats vary throughout the world and it's often difficult to find a human-friendly date format that feels intuitive to everyone. The advantage of dates formatted like `2017-07-17` is that they follow the order of largest to smallest units: year, month, and day.

maybe it would be better to switch to YYYY-MM-DD ?

**Comment by tombh** [comment]
I'd like to propose that Pygls starts using an automatic CHANGELOG generator, such as https://github.com/orhun/git-cliff. And that we require [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) messages. The CHANGELOG file doesn't have to be auto-populated in CI, although I would like to try that at first. More than anything I would just like it to be populated by a standard tool and we could edit it after the auto-population.

**Comment by tombh** [comment]
This was fixed in https://github.com/openlawlibrary/pygls/pull/349 by automating with https://github.com/orhun/git-cliff
