### ISSUE TITLE
Is it possible to drop typeguard?

### ISSUE THREAD

**Issue by karthiknadig** [openlawlibrary/pygls#409]
This dependency often causes issues:
https://github.com/microsoft/vscode-black-formatter/issues/265
https://github.com/microsoft/vscode-pylint/issues/446
https://github.com/microsoft/vscode-isort/issues/344

All caused by outdated version of typing extension in users environment.

`lsprotocol` includes the Type for the Options supported for each request. Would it be possible to use that to validate options without using typeguard?

**Comment by tombh** [comment]
I think this issue is related? #406 "Consider removing upper bounds on dependencies"

**Comment by alcarney** [comment]
I'm open to the idea.

As far as I know, the only place we use it is when we [check](https://github.com/openlawlibrary/pygls/blob/8f601029dcf3c7c91be7bf2d86a841a1598ce1f0/pygls/feature_manager.py#L192) to make sure the user passes the right type to the `@server.feature` decorator

During the initial migration to `lsprotocol` I tried replacing our [`is_instance`](https://github.com/openlawlibrary/pygls/blob/8f601029dcf3c7c91be7bf2d86a841a1598ce1f0/pygls/lsp/__init__.py#L134) function (which uses `typeguard`) with Python's regular `isinstance()` function - but couldn't make it work, or at least I didn't try very hard. I can't remember the details now, but it was either throwing errors when it shouldn't have, or was letting some errors slip through.

Assuming we can figure out a replacement for `is_instance` I'm all for it.

**Comment by karthiknadig** [comment]
@alcarney Are there tests I can verify the fix against?

**Comment by alcarney** [comment]
They're not comprehensive, but there are a few test cases like [this one](https://github.com/openlawlibrary/pygls/blob/8f601029dcf3c7c91be7bf2d86a841a1598ce1f0/tests/test_feature_manager.py#L102) in `test_feature_manager.py`
