### ISSUE TITLE
LSP update with some breaking changes

### ISSUE THREAD

**Issue by karthiknadig** [openlawlibrary/pygls#410]
There is an update to LSP which removed all the anonymous types from the LSP json model. This means that all the generated types names that included `*_Type*` form of classes are gone.
https://github.com/microsoft/vscode-languageserver-node/pull/1308/files

Here is my plan to address this, let me know if that works for you: Make a stable release of `lsprotocol` (version 2023.0.0) based on the current pre-release version 2023.0.0b1. This will allow pygls to pin on `2023.0.0` stable. Then, I will publish a pre-release version 2024.0.0a1, and `pygls` can have a pre-release version that pins to `2024.*` as it comes out.

**Comment by alcarney** [comment]
Makes sense to me :)

**Comment by karthiknadig** [comment]
Thank you.
