### ISSUE TITLE
Wrong type on server.start_io

### ISSUE THREAD

**Issue by OhioDschungel6** [openlawlibrary/pygls#496]
The server.start_io method has 2 optional arguments which are typed with TextIO.
Entering an TextIO object crashes the language server.

Entering a BinaryIO object makes everything work.
This seems reasonable as the default case also uses an BinaryIO object (see line 239):
` transport = StdOutTransportAdapter(stdin or sys.stdin.buffer, stdout or sys.stdout.buffer)`

sys.stdin.buffer has type BinaryIO

Solution:
in server.py change
`def start_io(self, stdin: Optional[TextIO] = None, stdout: Optional[TextIO] = None):`
to
`def start_io(self, stdin: Optional[BinaryIO] = None, stdout: Optional[BinaryIO] = None):`

**Comment by tombh** [comment]
Like this? https://github.com/openlawlibrary/pygls/pull/497

**Comment by OhioDschungel6** [comment]
Yes exactly :) Thanks!

**Comment by tombh** [comment]
Merged into main ✅ Please let us know if there's any more problems.
