### ISSUE TITLE
Can't Escape Square Brackets In Markdown Text For Hover

### ISSUE THREAD

**Issue by MinimalEffort07** [openlawlibrary/pygls#514]
Unsure if this is a pygls issue or a LSP client issue but I can't seem to escape square brackets in text passed to type.Hover's value field. 

```python
    return types.Hover(
        contents=types.MarkupContent(
            kind=types.MarkupKind.Markdown,
            value="[some text]"),
        ).
```
```plaintext
value = "[some text]" = outputs > some text
value = "\[some text\]" => \[some text\]
value = "\\[some text\\]" => \[some text\]
value = "\\\\[some text\\\\]" => \\some text\\
value = r"\\\\[some text\\\\]" => \\\\some text\\\\
value = r"\\[some text\\]" => \\some text\\
value = r"\[some text\]" => \[some text\]
value = r"[some text]" => some text
```

I would like to escape the square brackets so that when I hover over a word I see:
[some text]

Im using pygls==2.0.0a2 and neovim v0.11.0-dev for LSP client.

**Comment by tombh** [comment]
I added a test for square brackets and it seems to work https://github.com/openlawlibrary/pygls/commit/c58d933ec38eb6c4d287679629c7992a79c25a3d So my first thought is that this might be something to do with Neovim. But I don't want that to be the last word on the matter. Maybe you could try playing with that test to see if you can find any clues?

It's run with: `poetry run pytest tests/e2e/test_hover.py`

**Comment by MinimalEffort07** [comment]
Thanks for adding the test Tom. It must be with related to how Neovim is parsing the markdown then Cheers.
