### ISSUE TITLE
Completion: Filtering the suggestions does not work when using the CompletionItem.textEdit property and setting the CompletionList.isInComplete to True

### ISSUE THREAD

**Issue by OliverSchmitt** [openlawlibrary/pygls#66]
The Problem is that filtering the suggestions in the drop down menu of the client does not work if the `CompletionList.isInComplete` property is set to `True` and the `CompletionItem.textEdit` of an element of the `CompletionList` is set.

The simplest example for the problem is a small extension to the exmaple server provided in the GitHub repository. It just adds a simple completion feature:

```python
@server.feature(COMPLETION)
def simple_completion(ls: LanguageServer, params: CompletionParams):
    # Equivalent TextEdit to default insertion
    line_number = params.position.line
    start = Position(line_number, params.position.character - 1)
    edit_range = Range(start, start)
    text_edit = TextEdit(edit_range, new_text="Inserted with textEdit")

    return CompletionList(False, [CompletionItem(
                                    label="Label",
                                    filter_text="filter_for",
                                    insert_text="Inserted with insert_text",
                                    # text_edit=text_edit
                                )]
                         )
```

I verified that `text_edit` is equivalent to the default insertion of `insert_text`.

I have tried the 4 combinations of changing the `isInComplete` property and using either `insert_text` or `text_edit` and can confirm that the other 3 combinations work.

Is this intended behavior? It makes it impossible to update `CompletionItem.filterText` in the recomputation of the completion suggestions.

**Comment by danixeee** [comment]
Hello @OliverSchmitt, 

from LSP specs:

```
interface Position {
	/**
	 * Line position in a document (zero-based).
	 */
	line: number;

	/**
	 * Character offset on a line in a document (zero-based). Assuming that the line is
	 * represented as a string, the `character` value represents the gap between the
	 * `character` and `character + 1`.
	 *
	 * If the character value is greater than the line length it defaults back to the
	 * line length.
	 */
	character: number;
}
```

both `line` and `character` fields are _zero-based_.

Your code works if cursor is not at Position(0,0), so I believe you just need to change the line where you set a start position to:

```python
start = Position(line_number, params.position.character)
```

Hope this helps and hope you like _pygls_!

**Comment by OliverSchmitt** [comment]
Hello @danixeee 
this fiixed the problem, thank you for your help.
Apparently I made a mistake in the verification of the `text_edit`. When I first tried it i used `Range(params.pos, params.pos)` but you actually need a new position instance to make it work.
