### ISSUE TITLE
Provide a method to access client capabilities

### ISSUE THREAD

**Issue by dinvlad** [openlawlibrary/pygls#71]
It appears that the current LanguageServer API does not provide a way to programmatically access client capabilities. It's important to properly detect when client doesn't support a certain feature, so as to not generate a request that will fail. For example, the client may not support `workspace/configuration`, and so `ls.get_configuration()` request fails, which then crashes the client (and we don't always have control over client code).

Would it be possible to add something like `ls.client_capabilities()` to request them? It would just directly return information cached from `initialize` request.

Thanks!

**Comment by danixeee** [comment]
Hello @dinvlad,

There is already a similar issue https://github.com/openlawlibrary/pygls/issues/59.
I just pushed my branch with changes that you need, but there should be some more work since I added an option to (un)register capability which should change cached server capabilities. I won't merge it until I finish that work, but you can install _pygls_ directly from branch `danixeee/capabilities`.

**Comment by dinvlad** [comment]
Thanks @danixeee, I saw that issue but I’m not sure if it addresses this directly. Some server capabilities don’t mirror those from the client, like `workspace/configuration`. It would be nice to have a way to directly access `InitializeParams` (for other reasons as well, like to find `rootUri`), which seems like the only way to access the value of `workspace/configuration`.

**Comment by dinvlad** [comment]
Apologies - just read the code in your branch. Seems like it’s what we need for client capabilities! It would still be nice to also have access to other initialization params, like `rootUri`.

**Comment by danixeee** [comment]
@dinvlad `rootUri` can be accessed from the `Workspace`. Take a look [here](https://github.com/openlawlibrary/pygls/blob/master/pygls/workspace.py#L218).

There is another way, which I recommend if you want to use the latest _pygls_ from PyPI.
Every _user-registered_ language feature (registered with `@server.feature(...)`) is called after _built-in_ language feature. For e.g., when initialization request is received, _pygls_ automatically creates workspace and calculates server capabilities in [built-in initialize method](https://github.com/openlawlibrary/pygls/blob/master/pygls/protocol.py#L532) and if you register the same _initialize_ method, it will be called and you can do anything you want:

```python
@ json_server.feature(INITIALIZE)
def initialize(ls, params: InitializeParams):     # <- called after built-in initialize method
    ls.client_capabilities = params.capabilities
```

This should work until we close the issue #59. Hope this helps!

**Comment by dinvlad** [comment]
Awesome, understood. I thought the params here are the ones passed in the response, not the request. Closing this issue in anticipation for #59.

Thank you!
