### ISSUE TITLE
Standalone publishable extension

### ISSUE THREAD

**Issue by TiemenSch** [openlawlibrary/pygls#74]
I'm currently experimenting with pygls (great so far!) and while things look promising, I'm struggling with setting up a process which results in a single installable VSCode extension.

Right at this moment, I'm trying to compile the server script with [Nuitka](https://nuitka.net/), which results in a single executable instead of having to point to an external Python distribution with pygls installed.

Regardless, I was wondering how I can build a single extension that I could install into any VSCode installation (e.g. it should include both client/server).

How would I go about that? I'm not as comfortable with JS/Node as I'm with Python.

**Comment by danixeee** [comment]
I haven't worked with _Nuitka_, but I tried `PyInstaller` for creating a single executable, although not with _pygls_. Anyway, you would need to include executables for _all_ targeting platforms while packaging the extension which can result in big extension size.
I am working on [this extension](https://github.com/textX/textX-LS) for a python tool, and first time extension gets activated, it creates virtual environment and installs necessary dependencies (preinstalled python is required).
You can also you [post install scripts](https://github.com/Microsoft/vscode/issues/23251#issuecomment-440224043) in extension manifest.

**Comment by TiemenSch** [comment]
So if we assume an executable with the name ``json_server`` were to be found on path, which then starts the language server just like https://github.com/openlawlibrary/pygls/blob/master/examples/json-extension/server/__main__.py 
does, how would I have to change the extension?

**Comment by TiemenSch** [comment]
I guess I'm just having trouble in flattening the ``client`` and ``server`` structure into a "single package.json" setup package.

**Comment by TiemenSch** [comment]
The good news is that everything works when I replace 
```javascript
client = startLangServer(pythonPath, ["-m", "server"], cwd);
```
with my self-built executable:
```javascript
client = startLangServer("json_server", [], cwd)
```
everything "just" works. 

Any ideas? I'll keep learning about the VS Code extension structure in the meantime.

**Comment by TiemenSch** [comment]
I took the liberty of creating a PR. I would appreciate any feedback! With some adjustment, this could make a useful template for an LSP extension where the LSP is provided as an executable instead of Node/Python/whatever.

**Comment by danixeee** [comment]
Hello @TiemenSch, sorry for not responding immediately, I am currently busy with other projects. Thank you for the PR, I will find some time to review your work at the begging of the next week. I hope it's working for you now and you are not blocked.

**Comment by TiemenSch** [comment]
Sure! I would be particularly interested to see how we could incorporate "hot reloading" of the TCP server while the extension remains active, as that would make debugging of LSPs an absolute breeze!

Essentially, you could run the Python script directly from your dev environment, and only use the compiled executable (which should be available on path or from settings) in production.

**Comment by TiemenSch** [comment]
Hi @danixeee,

So far I'm successfully using Nuitka in my personal dev environment! Although I haven't been able to get the VS Code extension to reconnect after you restart the server process. That is an entirely different issue, though, so I would suggest closing this.

For simplicity's sake, I changed my mind and would no longer want to put this directly inside the/any demo extension.
