### ISSUE TITLE
Implement web-socket server

### ISSUE THREAD

**Issue by danixeee** [openlawlibrary/pygls#85]
Currently _pygls_ supports two types of connections:

- TCP/IP
- IO (stdin/stdout)

We want to add another type of connection - _web-sockets_.

**Comment by bollwyvl** [comment]
Sounds cool!

The websocket approach is not precisely standardized: as i mentioned, the convention for how many URLs should be exposed appears to be _n_, one per language server. Having _1_, and doing the negotiation at the message level, sounds really good to me, but there might be deep parts of the protocol model that I don't yet understand!

**Comment by MatejKastak** [comment]
I think the base implementation is resolved in https://github.com/openlawlibrary/pygls/pull/129 . Maybe we can close this issue?

**Comment by danixeee** [comment]
@MatejKastak you are right. Closing the issue, thanks!
