### ISSUE TITLE
Run test suite on multiple python versions and also on linux

### ISSUE THREAD

**Issue by perrinjerome** [openlawlibrary/pygls#96]
https://github.com/openlawlibrary/pygls/blob/master/appveyor.yml only runs tests for python3.5 on windows.

It would be nice to run tests on other python versions, isn't it ?

I started a patch that would run tests on a matrix like this: https://ci.appveyor.com/project/perrinjerome/pygls/builds/29961016 . Patch is still very dirty, there's lots of duplication ( it's https://github.com/perrinjerome/pygls/commit/8879078854e2c2ccf22b5c6b380032c0e8a8a2d9 ), but what are your thoughts on this ?  And about using tox ? (tox makes it easier for developers to run test suite on multiple python versions as long as they have these versions installed locally)

**Comment by danixeee** [comment]
I agree. We could update `appveyor.yaml` to run _tox_ just on PRs. That way building regular commits will be faster, but on the other hand we will be sure that _pygls_ is tested across different python versions and platforms before any PR is merged. What are your thoughts?

**Comment by perrinjerome** [comment]
Thank you for feedback.
I think the build is not so long, in total it takes less about 5 minutes, so it seems acceptable, isn't it ?
If I understand correctly, appveyor runs "jobs" sequentially under free plan and to run jobs in parrallel a pay plan is needed ( https://ci.appveyor.com/billing ).

There's one thing that I don't understand, are this `%OLL_GIT_USER_NAME%` and `% OLL_GIT_EMAIL%` used ? 

https://github.com/openlawlibrary/pygls/blob/ad1a1bad8c3f9821214699866ed10e2e1e8061e0/appveyor.yml#L38-L41

**Comment by danixeee** [comment]
It's fine then. I don't know about the plans, we will need to take a look.

> There's one thing that I don't understand, are this %OLL_GIT_USER_NAME% and % OLL_GIT_EMAIL% used ?

I didn't write that file, but I think it's needed for this:

https://github.com/openlawlibrary/pygls/blob/ad1a1bad8c3f9821214699866ed10e2e1e8061e0/appveyor.yml#L23-L24

**Comment by perrinjerome** [comment]
Thanks for feedback. I'm sorry I was not cleared, I mentioned the plans, because I have been investigating a bit why jobs were not running sequentially, I thought that maybe there was something wrong in the `appveryor.yml`.

**Comment by danixeee** [comment]
If you already have a modified script you could push it and we can see. I am using _Azure_ for multi-platform jobs in one of my OS project, but I guess we will stick with _appveyor_ for _pygls_.

So, you suggested running a _tox_ on multiple platform with multiple python versions? I think that's fine.

**Comment by perrinjerome** [comment]
I pushed the current "work in progress" state in https://github.com/openlawlibrary/pygls/pull/100 let me know what you think.
